{
  universes(first: 1) {
    id
    owner
    chargedParticles {
      id
      owner
      whitelisted {
        id
        contractAddress
        state
      }
      externalContractSettings {
        id
        contractAddress
        liquidityProvider
        assetDepositMin
        assetDepositMax
      }
      nftCreatorSettings {
        id
        contractAddress
        tokenId
        creatorAddress
        annuityPercent
      }
      chargedNftState {
        id
        contractAddress
        tokenId
        lastKnownOwner
        dischargeApproval
        releaseApproval
        timelockApproval
        dischargeTimelock
        releaseTimelock
        assetToBeReleasedBy
      }
      genericBasketManager {
        id
        owner
        name
        address
        paused
        baskets {
          id
          address
          contractAddress
          tokenId
          totalTokens
          tokenBalances {
            id
          	contractAddress
          	tokenId
            nftTokenAddress
            nftTokenIds
          }
        }
      }
      genericWalletManager {
        id
        owner
        name
        address
        paused
        wallets {
          id
          address
          contractAddress
          tokenId
          assetTokens
          assetBalances {
            id
            assetToken
          	contractAddress
          	tokenId
            principal
          }
        }
      }
      aaveWalletManager {
        id
        owner
        name
        address
        paused
        aaveBridge
        wallets {
          id
          address
          contractAddress
          tokenId
          assetTokens
          nftCreator
          nftCreatorAnnuityPct
          nftCreatorAnnuityRedirect
          assetBalances {
            id
            assetToken
          	contractAddress
          	tokenId
            principal
            ownerInterestDischarged
            creatorInterestDischarged
          }
        }
      }
    }
    ionToken {
      id
      owner
      holders {
        id
        address
        balance
      }
    }
    esaMultiplier {
      id
      assetToken
      multiplier
    }
  }

  wBosons {
    id
    wBoson
    account

    wBosonUri

    name
    description
    thumbnail
    image

    email
    twitter
    website
  }

  protonNFTs {
    id
    tokenId
    proton {
      id
    }
    owner
    creator
    metadataUri

    particleType
    creatorAnnuity
		salePrice
    resaleRoyalties

    name
    decimals
    symbol
    description
    external_url
    animation_url
    youtube_url
    icon
    image
    background_color

    attributes {
      id
      name
      value
    }
  }

  nftTxHistories {
    id
    contractAddress
    tokenId
    timestamp
    eventType
    eventData
  }

  ionHolders(where: {
    address_in: [
    	"0x6ad155dec215c9ee3a6edebcde8e3c528dc2d0ef",
      "0xfc15c29fac2b19f29bbf9fdcc6f8e441604d8c27"
    ]}
  ) {
    id
    address
  }
}
